"""Fork a finished play run (engine_re.play_agent) at one of its turns, so that run_play resumes it from there.

    uv run --no-sync python -m engine_re.tools.fork_run --src runs/engine-play/<run>/<game> --turn T \\
        --out runs/engine-play/<fork>/<game> [--environments-dir environment_files] [--no-verify] [--force]

    uv run --no-sync python -m engine_re.run_play --games <game> --out runs/engine-play/<fork> --max-turns T+100 ...

The source is never written (it is DVC-checked-out data). The fork is a copy of the game directory truncated to
the state right after turn T finished: the moves of turn T played, the message created at the end of turn T (the
PLAN or FIT message the model reads at turn T + 1) said. --max-turns on the resume is the absolute turn count.

What the fork holds:

- transcript.jsonl: the records logged before the model's answer of turn T + 1 (every record carries the turn the
  harness was on: those of the end of turn T, the message included, carry T; the only exception, the "images"
  record of a FIT message's pictures, carries T + 1 and precedes the message, and it is kept with it). A trailing
  resume of the source at that same point (its "replay", resume note and "resumed" records) is dropped: the fork's
  own resume makes them again. One record is appended, {"fork": {"source", "turn", "steps"}}: the transcript page
  shows where the fork starts, and the resume counts the cost and the minutes from it on (below).
- tests.jsonl: the records with turn <= T.
- trace/ and visible_trace/: the steps played by turn T (the "move" records, the automatic RESETs among them;
  step 0 is the opening RESET), the meta's unexplained steps and resync points among them, and the out-of-step
  mark when the engine was out of step at T; visible_trace/ ends at the step the model was on (its focus: the
  fit round's step, or the last step played).
- engine_versions/: the versions created by turn T (the "engine_change" records); workspace/engine.py is the
  last of them (every write to engine.py is a version; the fork checks it against the sha256 of the last test).
- engine_committed.py: the engine of the last "commit" record by turn T, or the opening's engine when there is
  none yet; engine_committed.support.json is regenerated by a full replay of it over the kept steps (tester
  .replay_test's support map over the steps it reproduces: all of them, or, in a fit round, those before the
  round's step, as the commit and the matched moves had built it); engine_best.py is the best engine among the kept tests
  (engine_files.best_key) when that version exists. Each is left out when it cannot be made; the resume copes
  (no support margin until the next commit; undo_edit(to="best") refused until a test).
- result.json: status "running", turns T, the counts as _restore reads them (batches, moves, mismatches, fit
  rounds, phase turns, the per-step token counts, the committed engine's hash, the phase), the usage summed over
  the kept turns, and `forked_from` {"source", "turn", "steps", "cost_usd", "minutes"}: the source and the budget
  it had spent at T. Cost and minutes are set to 0: the fork is a new experiment with its own budget (--max-cost,
  --max-minutes count what the fork spends), and PlayAgent._restore takes a fork's cost and minutes from the
  records after the "fork" record only, so the source's spending cannot stop it. Output tokens stay as the source
  spent them (--max-output-tokens is absolute, like --max-turns), since they measure the conversation's length.
- images/: the pictures of turns <= T (the rebuilt conversation reads the ones its messages show).
- workspace/: engine.py (above) and notes.md as the template (prompts.NOTES_TEMPLATE); every other file the model
  wrote is left out. notes.md is written by the model's python cells (edit_file(path="notes.md", ...)), which a
  resume replays with edits disabled; the marker fork.json {"source", "turn", "steps"} makes the first resume's
  replay apply the edits to files other than engine.py (helpers.REPLAY_FILES), so notes.md and the other files
  are rebuilt from the kept cells alone and nothing written after turn T leaks in; the marker is then removed.
- artifacts/<game_id>_p0_events.jsonl (the viewer sidecar) is written from the kept trace when the real game
  is replayed (--no-verify skips it; a resume writes it anyway).
- <out>/../config.json gets {"forks": {<game>: {"forked_from", "fork_turn", "steps"}}}; run_play keeps that key.

Unless --no-verify, the real game is replayed through the kept trace (live_game.LiveGame, the determinism check
every resume relies on) and the committed engine is tested on it; the summary printed says where the game is.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any

from engine_re.agent import PYTHON_PAUSED, RESUME_NOTE, Usage
from engine_re.engine_files import best_key
from engine_re.play_agent import AUTO_RESET_NOTE, COMMITTED_FILE, FORK_FILE, SUPPORT_FILE, PlayResult
from engine_re.prompts import NOTES_FILE, NOTES_TEMPLATE
from engine_re.trace import Trace

_IMAGE_TURN = re.compile(r"^turn(\d+)_")
_RESUME_NOTE_HEAD = RESUME_NOTE.split("{", 1)[0]


class ForkError(RuntimeError):
    pass


def _kind(record: dict[str, Any]) -> str | None:
    return next((k for k in record if k not in ("turn", "phase", "step", "elapsed_min")), None)


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")


# --- the truncation ------------------------------------------------------------------------------


def cut_records(records: list[dict[str, Any]], turn: int) -> list[dict[str, Any]]:
    """The transcript records of the state after turn `turn` finished: everything logged before the model's answer
    of turn + 1 (the "finish_reason" record with a greater turn), less a trailing resume at that point."""
    cut = next((i for i, r in enumerate(records) if "finish_reason" in r and int(r.get("turn") or 0) > turn), len(records))
    kept = list(records[:cut])
    if not any("finish_reason" in r and int(r.get("turn") or 0) == turn for r in kept) and turn > 0:
        raise ForkError(f"the transcript has no model turn {turn} (it has {max((int(r.get('turn') or 0) for r in records), default=0)})")
    # a resume of the source right there: {"replay"}, the resume note, {"resumed"} (the fork's own resume makes them)
    while kept and _kind(kept[-1]) in ("resumed", "replay") or (
        kept and _kind(kept[-1]) == "message" and kept[-1]["message"].get("role") == "user"
        and isinstance(kept[-1]["message"].get("content"), str) and kept[-1]["message"]["content"].startswith(_RESUME_NOTE_HEAD)
    ):
        kept.pop()
    return kept


def cut_tests(tests: list[dict[str, Any]], turn: int) -> list[dict[str, Any]]:
    return [t for t in tests if int(t.get("turn") or 0) <= turn]


def fork_state(records: list[dict[str, Any]], turn: int) -> dict[str, Any]:
    """What the kept records say of the state at the fork: the steps played ("steps", step 0 included), the step the
    model is on ("focus"), the phase, the current version of engine.py, the committed engine's sha, the out-of-step
    mark, and how many resumes the source had by then."""
    moves = [int(r["move"]["index"]) for r in records if "move" in r]
    steps = (max(moves) if moves else 0) + 1
    focus = steps - 1
    phase = "plan"
    for r in records:  # as agent._rebuild_conversation and play_agent._resume_conversation read them
        if "step_start" in r:
            focus, phase = int(r["step_start"]["step"]), "fit"
        elif "advance" in r:
            focus, phase = int(r["advance"]["next"]), "fit"
        elif "resumed" in r:
            focus = int(r["resumed"]["step"])
        elif "plan" in r:
            focus, phase = int(r["plan"]["step"]), "plan"
        elif "refused_batch" in r or "fit_escape" in r:
            phase = "fit"
        elif "out_of_sync" in r:
            phase = "plan"
    phases = [r for r in records if "plan" in r or "step_start" in r or "advance" in r]
    if phases:
        seen = (phases[-1].get("plan") or phases[-1].get("step_start") or phases[-1].get("advance") or {}).get("steps")
        if seen is not None and int(seen) > steps:
            raise ForkError(f"the last phase message says {seen} steps were played, the move records {steps}")
    versions = [int(r["engine_change"]["version"]) for r in records if isinstance(r.get("engine_change"), dict) and r["engine_change"].get("version")]
    version = max(versions) if versions else 1
    commits = [r["commit"] for r in records if "commit" in r]
    if commits:
        committed_sha = commits[-1].get("engine_sha")
    elif phases and "plan" in phases[0]:  # the opening's engine, committed without a record (play_agent._stepwise_start)
        opening = [int(r["engine_change"]["version"]) for r in records
                   if isinstance(r.get("engine_change"), dict) and r["engine_change"].get("version") and int(r.get("turn") or 0) == 0]
        committed_sha = {"version": max(opening) if opening else 1}
    else:
        committed_sha = None
    out_of_sync = None
    for r in records:
        if "out_of_sync" in r:
            out_of_sync = int(r["out_of_sync"]["from"])
        elif "resync" in r:
            out_of_sync = None
    return {
        "turn": turn, "steps": steps, "focus": focus, "phase": phase, "version": version, "committed_sha": committed_sha,
        "out_of_sync": out_of_sync, "resumes": sum(1 for r in records if "resumed" in r),
    }


def cut_trace(trace: Trace, steps: int, out_of_sync: int | None) -> Trace:
    """The trace's first `steps` steps, with the meta entries that apply to them."""
    last = steps - 1
    meta = {k: v for k, v in trace.meta.items() if k not in ("ignore", "resync", "out_of_sync", "focus")}
    ignore = sorted(int(i) for i in trace.meta.get("ignore") or [] if int(i) <= last)
    resync = {str(k): v for k, v in (trace.meta.get("resync") or {}).items() if int(k) <= last}
    if ignore:
        meta["ignore"] = ignore
    if resync:
        meta["resync"] = resync
    if out_of_sync is not None and out_of_sync <= last:
        meta["out_of_sync"] = out_of_sync
    return Trace(trace.game_id, trace.steps[:steps], meta)


def _fit_rounds(rounds: list[dict[str, Any]], records: list[dict[str, Any]], turn: int) -> list[dict[str, Any]]:
    """The source's fit rounds that had started by `turn`, the one open then reopened."""
    out = []
    for r in rounds:
        if int(r.get("start_turn") or 0) > turn:
            continue
        r = dict(r)
        if r.get("end_turn") is None or int(r["end_turn"]) > turn:
            start = int(r.get("start_turn") or 0)
            r.update(end_turn=None, turns=None, accepted=None, commits=sum(1 for c in records if "commit" in c and start <= int(c.get("turn") or 0) <= turn))
            r.pop("end", None)
            if r.get("escape_offered") is not None and int(r["escape_offered"]) > turn:
                r.pop("escape_offered")
        out.append(r)
    return out


def fork_result(source: dict[str, Any], records: list[dict[str, Any]], tests: list[dict[str, Any]], state: dict[str, Any],
                trace: Trace, src: str, committed_sha: str | None) -> dict[str, Any]:
    """result.json of the fork: the source's, with every count truncated to the kept records (as PlayAgent._restore
    reads them back), status "running", cost and minutes 0, and forked_from."""
    turn = state["turn"]
    usage = Usage()
    tool_calls: dict[str, int] = {}
    thoughts = 0
    for r in records:
        if "finish_reason" in r:
            usage.add(r.get("usage") or {})
            thoughts += 1
        elif "tool" in r:
            tool_calls[r["tool"]] = tool_calls.get(r["tool"], 0) + 1
    spent = {"cost_usd": round(usage.cost_usd, 6), "minutes": max((float(r.get("elapsed_min") or 0.0) for r in records), default=0.0)}
    usage.cost_usd = 0.0
    full_tests = [t for t in tests if t.get("level") is None and t.get("from_level") in (None, 0)]
    best = max(full_tests, key=best_key, default=None)
    commits = [{"turn": r["turn"], **r["commit"]} for r in records if "commit" in r]
    batch_log = [r["batch"] for r in records if "batch" in r]
    moves = [r["move"] for r in records if "move" in r]
    refused = sum(1 for r in records if "tool" in r and r["tool"] == "commit_moves" and str(r.get("output", "")).startswith("Not sent:")
                  and "the game is won" not in str(r.get("output", ""))[:60])
    phase_turns = {"plan": 0, "fit": 0}
    last_tool: dict[int, str] = {}
    for r in records:  # _end_of_turn counts the phase a turn ends its tool calls in (an idle turn counts nothing)
        if "tool" in r:
            last_tool[int(r.get("turn") or 0)] = str(r.get("phase") or "plan")
    for t, phase in last_tool.items():
        if 1 <= t <= turn:
            phase_turns[phase] = phase_turns.get(phase, 0) + 1
    steps = state["steps"]
    step_tokens = [int(v) for v in (source.get("step_tokens") or [])][: steps - 1]
    step_tokens += [int(usage.completion_tokens)] * (steps - 1 - len(step_tokens))
    r = PlayResult(
        game=source["game"], model=source["model"], status="running", turns=turn, minutes=0.0, usage=usage, tool_calls=tool_calls,
        tests_run=sum(1 for t in tests if t.get("auto") not in ("opening", "episode", "advance")),
        first_pass_turn=next((t["turn"] for t in full_tests if t.get("passed")), None),
        best=({k: v for k, v in best.items() if k not in ("time", "from_level")} if best else None), final=None,
        commit_message=commits[-1].get("message") if commits else None,
        commit_calls=sum(1 for r in records if "tool" in r and r["tool"] in ("commit_engine", "finish")),
        error=None, trace_steps=steps, resumes=state["resumes"], nudges=sum(1 for r in records if "nudge" in r),
        auto_tests=sum(1 for r in records if "auto_test" in r),
        python_paused=sum(1 for r in records if "tool" in r and str(r.get("output", "")).startswith(PYTHON_PAUSED[:40])),
        engine_changes=sum(1 for r in records if "engine_change" in r and r.get("by") != "harness"),
        match=source.get("match", "final"), interface=source.get("interface", "simple"), images=bool(source.get("images", True)),
        image_messages=sum(1 for r in records if "images" in r), provider_errors=0, opening=source.get("opening") or {},
        mode="play", context=source.get("context", "compact"), thinking_budget=source.get("thinking_budget"),
        step=state["focus"], passing_prefix=None, advances=commits,
        game_id=source.get("game_id", ""), outcome="won" if trace[-1].state == "WIN" else "playing", actions=max(0, steps - 1),
        levels_completed=max((s.levels_completed for s in trace.steps), default=0), win_levels=int(trace[0].win_levels),
        actions_per_level=_actions_per_level(trace), baseline_actions=source.get("baseline_actions"), score=None,
        batches=sum(1 for b in batch_log if b.get("note") != AUTO_RESET_NOTE), refused_batches=refused, moves_sent=len(moves),
        mismatches=sum(1 for m in moves if m.get("ok") is False), auto_resets=sum(1 for b in batch_log if b.get("note") == AUTO_RESET_NOTE),
        plan_nudges=sum(1 for r in records if "plan_nudge" in r), batch_log=batch_log,
        fit_rounds=_fit_rounds(source.get("fit_rounds") or [], records, turn), phase_turns=phase_turns, step_tokens=step_tokens,
        phase=state["phase"], committed_sha=committed_sha, fit_turns=source.get("fit_turns"), cut_untested=bool(source.get("cut_untested")),
        escapes=sum(1 for r in records if "out_of_sync" in r), out_of_sync=state["out_of_sync"],
        unexplained=[int(i) for i in trace.meta.get("ignore") or []], resync=dict(trace.meta.get("resync") or {}),
        forked_from={"source": src, "turn": turn, "steps": steps, **spent},
    )
    return asdict(r)


def _actions_per_level(trace: Trace) -> list[int]:
    counts = [0] * max(1, trace[0].win_levels if len(trace) else 1)
    for k in range(1, len(trace)):
        counts[min(trace[k - 1].levels_completed, len(counts) - 1)] += 1
    return counts


# --- the fork --------------------------------------------------------------------------------------


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fork_run(src: Path, out: Path, turn: int, environments_dir: Path | None = Path("environment_files"), verify: bool = True,
             force: bool = False) -> dict[str, Any]:
    """Write the fork of `src` at `turn` into `out` (which must not exist); returns a summary. `src` is only read."""
    src, out = Path(src), Path(out)
    if not (src / "transcript.jsonl").exists() or not (src / "result.json").exists():
        raise ForkError(f"{src} is not a play run directory (transcript.jsonl and result.json needed)")
    if out.exists():
        raise ForkError(f"{out} exists already")
    if out.resolve() == src.resolve() or out.resolve().is_relative_to(src.resolve()):
        raise ForkError("the fork cannot be written into the source")
    source = json.loads((src / "result.json").read_text(encoding="utf-8"))
    records = _load_jsonl(src / "transcript.jsonl")
    kept = cut_records(records, turn)
    state = fork_state(kept, turn)
    tests = cut_tests(_load_jsonl(src / "tests.jsonl"), turn)
    warnings: list[str] = []

    # engine.py and its versions
    versions_dir = src / "engine_versions"
    versions = [v for v in _load_jsonl(versions_dir / "versions.jsonl") if int(v["version"]) <= state["version"]]
    current = versions_dir / f"v{state['version']:04d}.py"
    if not current.exists():
        raise ForkError(f"{current} is missing: the fork's engine.py would be version {state['version']}")
    engine_sha = _sha(current)
    if tests and tests[-1].get("engine_sha") and tests[-1]["engine_sha"] != engine_sha:
        message = (f"the last test by turn {turn} (turn {tests[-1]['turn']}) ran engine {tests[-1]['engine_sha'][:12]}, but the last "
                   f"version by then, v{state['version']}, is {engine_sha[:12]}")
        if not force:
            raise ForkError(message + " (--force takes the version)")
        warnings.append(message)
    by_sha = {v["sha"]: int(v["version"]) for v in versions if v.get("sha")}
    by_sha.setdefault(engine_sha, state["version"])
    committed = state["committed_sha"]
    if isinstance(committed, dict):  # the opening's engine, by version
        path = versions_dir / f"v{committed['version']:04d}.py"
        committed = _sha(path) if path.exists() else None
    committed_version = by_sha.get(committed) if committed else None
    if committed and committed_version is None:
        warnings.append(f"the committed engine {committed[:12]} is not among the kept versions: no engine_committed.py")
        committed = None

    # the trace
    full = Trace.load(src / "trace")
    if state["steps"] > len(full):
        raise ForkError(f"the records say {state['steps']} steps were played by turn {turn}, the trace holds {len(full)}")
    trace = cut_trace(full, state["steps"], state["out_of_sync"])
    focus = min(int(state["focus"]), len(trace) - 1)

    # write
    out.mkdir(parents=True)
    trace.save(out / "trace")
    Trace(trace.game_id, trace.steps[: focus + 1], {**trace.meta, "focus": focus}).save(out / "visible_trace")
    fork_record = {"turn": turn, "fork": {"source": str(src), "turn": turn, "steps": state["steps"]}, "phase": state["phase"],
                   "step": focus, "elapsed_min": 0.0}
    _write_jsonl(out / "transcript.jsonl", kept + [fork_record])
    _write_jsonl(out / "tests.jsonl", tests)
    (out / "engine_versions").mkdir()
    for v in versions:
        shutil.copy(versions_dir / f"v{int(v['version']):04d}.py", out / "engine_versions" / f"v{int(v['version']):04d}.py")
    _write_jsonl(out / "engine_versions" / "versions.jsonl", versions)
    workspace = out / "workspace"
    workspace.mkdir()
    shutil.copy(current, workspace / "engine.py")
    (workspace / NOTES_FILE).write_text(NOTES_TEMPLATE, encoding="utf-8")
    if committed_version is not None:
        shutil.copy(versions_dir / f"v{committed_version:04d}.py", out / COMMITTED_FILE)
    full_tests = [t for t in tests if t.get("level") is None and t.get("from_level") in (None, 0)]
    best = max(full_tests, key=best_key, default=None)
    if best is not None and by_sha.get(best.get("engine_sha")) is not None:
        shutil.copy(versions_dir / f"v{by_sha[best['engine_sha']]:04d}.py", out / "engine_best.py")
    elif best is not None:
        warnings.append("the best tested engine is not among the kept versions: no engine_best.py")
    images = src / "images"
    shown = {part["path"] for r in kept if "message" in r and isinstance(r["message"].get("content"), list)
             for part in r["message"]["content"] if part.get("type") == "image_file" and part.get("path")}
    if images.is_dir():
        (out / "images").mkdir()
        for path in sorted(images.iterdir()):
            m = _IMAGE_TURN.match(path.name)
            if (m and int(m.group(1)) <= turn) or f"images/{path.name}" in shown:
                shutil.copy(path, out / "images" / path.name)
    missing = [p for p in shown if not (out / p).exists()]
    if missing:
        warnings.append(f"{len(missing)} picture(s) the kept messages show are missing from the source: {missing[:3]}")
    result = fork_result(source, kept, tests, state, trace, str(src), committed)
    (out / FORK_FILE).write_text(json.dumps({"source": str(src), "turn": turn, "steps": state["steps"], "created": time.strftime("%Y-%m-%dT%H:%M:%S")},
                                            indent=2) + "\n", encoding="utf-8")
    summary: dict[str, Any] = {
        "out": str(out), "turn": turn, "steps": state["steps"], "focus": focus, "phase": state["phase"], "records": len(kept),
        "tests": len(tests), "versions": state["version"], "engine_sha": engine_sha[:12],
        "committed": committed[:12] if committed else None, "spent": result["forked_from"], "warnings": warnings,
    }
    if verify:
        summary.update(_verify(out, result, trace, environments_dir, warnings))
    (out / "result.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    config_path = out.parent / "config.json"
    config = json.loads(config_path.read_text(encoding="utf-8")) if config_path.exists() else {}
    config.setdefault("forks", {})[out.name] = {"forked_from": str(src), "fork_turn": turn, "steps": state["steps"]}
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return summary


def _verify(out: Path, result: dict[str, Any], trace: Trace, environments_dir: Path | None, warnings: list[str]) -> dict[str, Any]:
    """Replay the real game through the kept trace (the viewer sidecar comes from it), and test the committed engine
    on it (its support map comes from a passing replay)."""
    from engine_re.live_game import LiveGame
    from engine_re.tester import replay_test

    found: dict[str, Any] = {}
    live = LiveGame(result["game"], environments_dir or Path("environment_files"), trace=trace)
    live.write_events(out)
    result["score"] = live.score()
    found["game"] = {"step": len(live.trace) - 1, "level": live.level, "levels_completed": live.levels_completed, "state": live.last.state,
                     "actions": live.actions, "score": live.score()}
    committed = out / COMMITTED_FILE
    if committed.exists():
        report = replay_test(committed, trace, failures=1, scratch_root=out, match=result.get("match", "final"))
        found["committed_test"] = {"passes": report.passed, "first_fail": report.summary().get("first_fail"), "passing_prefix": report.passing_prefix,
                                   "steps": report.total}
        # the map over the steps the committed engine reproduces: all of them, or, in a fit round, those before its step
        verified = report.passed or (report.first_fail == len(trace) - 1 and report.error is None)
        if verified and report.support:
            (out / SUPPORT_FILE).write_text(json.dumps(report.support), encoding="utf-8")
            found["support_steps"] = report.support.get("steps")
        else:
            warnings.append("the committed engine fails a step before the last one: no support map" if not verified else "no support map")
    engine = out / "workspace" / "engine.py"
    report = replay_test(engine, trace, failures=1, scratch_root=out, match=result.get("match", "final"))
    result["passing_prefix"] = report.passing_prefix
    found["engine_test"] = {"passes": report.passed, "first_fail": report.summary().get("first_fail"), "passing_prefix": report.passing_prefix,
                            "steps": report.total}
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path, required=True, help="the source game directory (read only)")
    parser.add_argument("--turn", type=int, required=True, help="fork after this turn finished")
    parser.add_argument("--out", type=Path, required=True, help="the fork's game directory (must not exist)")
    parser.add_argument("--environments-dir", type=Path, default=Path("environment_files"))
    parser.add_argument("--no-verify", action="store_true", help="do not replay the real game nor test the committed engine")
    parser.add_argument("--force", action="store_true", help="take engine.py's last version even when the last test ran another")
    args = parser.parse_args()
    try:
        summary = fork_run(args.src, args.out, args.turn, args.environments_dir, verify=not args.no_verify, force=args.force)
    except ForkError as exc:
        print(f"fork_run: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
