# REAP statistics for Qwen3.8-Flash-Next on Kaggle (RTX PRO 6000).
# Generated by exp/reap-flash-next/kaggle/push.py: edit the template there, not this copy.
import glob
import json
import os
import subprocess
import sys
import time
from pathlib import Path

CONFIG = json.loads(r"""__CONFIG__""")
OUT = Path("/kaggle/working/reap")
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")


def sh(cmd, check=False):
    print(f"$ {cmd}", flush=True)
    return subprocess.run(cmd, shell=True, check=check)


print("config:", json.dumps(CONFIG), flush=True)
sh("nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv")
_gpu = subprocess.run("nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits", shell=True,
                      capture_output=True, text=True).stdout.split()
if not _gpu or int(_gpu[0]) < 90_000:  # MiB; the int4 experts alone take 62 GB
    raise SystemExit(f"needs the 96 GB RTX PRO 6000, got {_gpu}: stopping before using quota")
sh("free -g; nproc; df -h /kaggle/working /tmp | tail -2")
# competition-attached notebooks on the RTX PRO 6000 run without internet: install from the wheels dataset
wheels = Path(glob.glob("/kaggle/input/**/transformers-*.whl", recursive=True)[0]).parent
sh(f"{sys.executable} -m pip install -q --no-index --find-links {wheels} --no-warn-conflicts "
   f"'transformers=={CONFIG['transformers']}'", check=True)
# fast gated delta rule (~12% faster); reap_model checks it against the reference and falls back if it differs
sh(f"{sys.executable} -m pip install -q --no-index --find-links {wheels} --no-deps --no-warn-conflicts "
   "flash-linear-attention==0.5.2 fla-core==0.5.2 einops")
sh(f"{sys.executable} -c \"import torch, transformers; print('torch', torch.__version__, torch.version.cuda, "
   f"torch.cuda.get_device_name(0), torch.cuda.get_device_capability(0), 'transformers', transformers.__version__)\"")

code_dir = Path(glob.glob("/kaggle/input/**/run_reap.py", recursive=True)[0]).parent
model_dir = next(Path(p).parent for p in glob.glob("/kaggle/input/**/model.safetensors.index.json", recursive=True)
                 if "intel" in p.lower())
trace_dirs = {}
for pattern, source in (("*arc-agi-3-milestone-2-solution*", "kaggle_v3"), ("*openrouter*", "openrouter")):
    for path in glob.glob(f"/kaggle/input/**/{pattern}/**/*_requests.jsonl*", recursive=True):
        trace_dirs.setdefault(source, str(Path(path).parent))
print("code:", code_dir, "\nmodel:", model_dir, "\ntraces:", trace_dirs, flush=True)
sh(f"ls {model_dir} | head -5; du -sh {model_dir}")

traces = " ".join(f"--traces {s}={d}" for s, d in trace_dirs.items() if s in CONFIG["sources"])
base = f"{sys.executable} {code_dir}/run_reap.py --model-dir {model_dir} {traces}"
if CONFIG.get("plan_all"):
    sh(f"{base} --out {OUT}/plan_all --plan-only")
for step in CONFIG["steps"]:
    started = time.time()
    sh(f"{base} --out {OUT}/{step['name']} {step['args']}")
    print(f"[kernel] step {step['name']} took {(time.time() - started) / 60:.1f} min", flush=True)
    sh(f"{sys.executable} {code_dir}/analyze.py {OUT}/{step['name']}")
sh(f"du -sh {OUT}; ls -R {OUT} | head -50")
